# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465f1c363429d1822a72e3bc9b34d903a0d9045cad36778b1c1d321f8562a35b9d90e6f1feeb1882f42dff052114e00da37b909f9562c2556c98e2bca8227d77

test:
  secret_key_base: d666a6da4b174dc6e53e2c35ec1a51231c6437438ea78e3f69cbf0be5da9dee4c5a02bafd3c70c2378ccc837308957e2cd4586b8442dc2dfc5f49df8e578d746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
